// Copyright (c) Matthias Wolf, Mawosoft.

// <auto-generated/>

#if !NET

#nullable enable

using Microsoft.CodeAnalysis;
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace System.Diagnostics
{
    [Embedded]
    internal sealed class UnreachableException : Exception;
}

namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Method, Inherited = false)]
    [Embedded]
    internal sealed class DoesNotReturnAttribute : Attribute;

    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue, Inherited = false)]
    [Embedded]
    internal sealed class NotNullAttribute : Attribute;
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    [Embedded]
    internal sealed class CallerArgumentExpressionAttribute : Attribute
    {
        public CallerArgumentExpressionAttribute(string parameterName) => ParameterName = parameterName;
        public string ParameterName { get; }
    }
}

namespace Microsoft.CodeAnalysis
{
    internal sealed partial class EmbeddedAttribute : Attribute;
}

namespace Mawosoft.PSReflector
{
    internal static class PolyFill
    {
        extension(ArgumentNullException)
        {
            public static void ThrowIfNull([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null)
            {
                if (argument is null) Throw(paramName);

                [DoesNotReturn] static void Throw(string? paramName) => throw new ArgumentNullException(paramName);
            }
        }
    }
}

#endif
